apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{.Values.healthz.name | default "healthz"}}
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    heritage: {{ .Release.Service | quote }}
    # This makes it easy to search for all components of a release using kubectl.
    release: {{ .Release.Name | quote }}
    # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
spec:
  template:
    metadata:
      labels:
        app: {{.Values.healthz.name | default "healthz"}}
        release: {{.Release.Name | quote }}
    spec:
      containers:
      - name: healthz
        image: {{.Values.healthz.image.repo | default "healthz"}}:{{.Values.healthz.image.tag | default "stable"}}
        imagePullPolicy: {{.Values.healthz.image.pullPolicy | default "IfNotPresent" | quote}}
        env:
          - name: HEALTH_LISTEN_ADDR
            value: "0.0.0.0:8080"
          - name: ETCDCTL_PEERS
            values: {{.Values.healthz.etcd.peers | default "http://localhost:4001,http://localhost:2380"}}
          - name: ETCDCTL_CERT_FILE
            value: /healthz-secret/etcdctl-cert.pem
          - name: ETCDCTL_KEY_FILE
            value: /healthz-secret/etcdctl-key.pem
          - name: ETCDCTL_CA_FILE
            value: /healthz-secret/etcdctl-ca.pem
          - name: HEALTH_CERT_FILE
            value: /healthz-secret/cert.pem
          - name: HEALTH_KEY_FILE
            value: /healthz-secret/key.pem
          - name: HEALTH_CA_FILE
            value: /healthz-secret/ca.pem
          - name: HEALTH_CHECK_INTERVAL
            value: {{.Values.healthz.checkInterval | default "1m"}}
          - name: HEALTH_KUBE_ADDR
            value: {{.Values.healthz.kube.addr | default ""}}
          - name: HEALTH_KUBE_NODES_THRESHOLD
            value: {{.Values.healthz.kube.nodesThreshold | default "75"}}
          - name: HEALTH_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.healthz.name | default "healthz"}}
                key: accesskey
        ports:
          - name: https
            protocol: TCP
            containerPort: 8080
        volumeMount:
          - name: healthz-secret
            mountPath: /healthz-secret
            readOnly: true
      volumes:
        - name: healthz-secret
          secret:
            secretName: {{.Values.healthz.name | default "healthz"}}
