apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.healthz.name | default "healthz"}}
data:
  accesskey: {{.Values.healthz.accesskey | default "" | b64enc | quote}}
{{if .Values.healthz.ssl.enabled}}
  cert.pem: {{.Values.healthz.ssl.cert | default "" | b64enc | quote}}
  key.pem: {{.Values.healthz.ssl.key | default "" | b64enc | quote}}
  ca.pem: {{.Values.healthz.ssl.ca | default "" | b64enc | quote}}
{{end}}
  etcdctl-cert.pem: {{.Values.healthz.etcd.cert | default "" | b64enc | quote}}
  etcdctl-key.pem: {{.Values.healthz.etcd.key | default "" | b64enc | quote}}
  etcdctl-ca.pem: {{.Values.healthz.etcd.ca | default "" | b64enc | quote}}
