apiVersion: v1
kind: Service
metadata:
  name: {{.Values.healthz.name | default "healthz"}}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: LoadBalancer
  ports:
  - port: {{.Values.healthz.port | default 8080}}
    protocol: TCP
    name: healthz
    targetPort: 8080
  selector:
    app: {{.Values.healthz.name | default "healthz"}}

